### ISSUE TITLE
An error appears when pressing the TAB key on the keyboard

### ISSUE THREAD

**Issue by terukaze1939** [bobbyrahmanda13/nvim#1]
Hello, I experienced an error when pressing the error button

![nvim-error](https://github.com/bobbyrahmanda13/nvim/assets/124257369/eda6be8b-0f40-4613-8d7c-1460ec5cb22b)

I'm using kali linux rolling, here's my specification

PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2023.3"
VERSION="2023.3"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
                       
I installed according to the procedure in README.md, thank you.

**Comment by bobbyrahmanda13** [comment]
The TAB button is a keymap from the nvim-cmp documentation, whether you have installed the plugin below or not, if you have installed it then this should not cause an error
![image](https://github.com/bobbyrahmanda13/nvim/assets/69358107/06611d3d-af70-4177-b33f-515a1a52b8e1)

anyway I got this from the documentation from [nvim-cmp](https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings)
![image](https://github.com/bobbyrahmanda13/nvim/assets/69358107/149b5743-af38-4583-b9a1-22c15beb47c7)

I also use it [Kali Linux](https://www.kali.org/) and [Termux](https://github.com/termux/termux-app)
![image](https://github.com/bobbyrahmanda13/nvim/assets/69358107/e05490fe-9a42-4c11-b1b3-d215204e3dc6)

**Comment by terukaze1939** [comment]
Oh my god, sorry my mistake. I just canceled the installation in the middle due to a very slow connection. And I think all the compiling parts have been worked. And it happened like this :D

Thank you for reply!
